### ISSUE TITLE
Feature to define the configuration page in KDE Plasma Search settings

### ISSUE THREAD

**Issue by bpavuk** [pluiedev/krunner-rs#3]
![image](https://github.com/user-attachments/assets/943dd145-3484-4c33-9399-9ef99b95412d)
Some plugins can be configured by user, and they have a settings icon near their name, but as far as I know, krunner-rs does not allow developers to implement the settings window

**Comment by pluiedev** [comment]
That is indeed currently a missing feature — will take a jab at it when I have time

**Comment by pluiedev** [comment]
So I actually looked into how it's done, and unfortunately I don't think there is a way to do it with krunner-rs. krunner-rs relies on the D-Bus interface Plasma exposes for runners not written with C++/Qt, as interfacing with Qt code from Rust is... not very fun in general. Unfortunately, directly using Qt is required for configuration modules as they are loaded as plugins, that must inherit from the [`KCModule`](https://api.kde.org/frameworks/kcmutils/html/classKCModule.html) class. There's also no real way to write a D-Bus abstraction for this interface as it has to use Qt widgets directly.

Maybe it would work if you were to compile and install the configuration module separately, as the module actually needs to be manually specified by the `X-KDE-ConfigModule` key in the runner plugin's JSON file anyway [(like this)](https://invent.kde.org/plasma/plasma-workspace/-/blob/master/runners/kill/plasma-runner-kill.json?ref_type=heads#L188), but for now I don't really see how this could be implemented on my end.
